### ISSUE TITLE
No support for Azure OpenAI endpoints

### ISSUE THREAD

**Issue by prasang-gupta** [relari-ai/continuous-eval#31]
There is no support for folks using Azure OpenAI endpoints instead of OpenAI endpoints (which is currently supported in LLMFactory).

**Comment by pantonante** [comment]
Good point, we are going to add it next week!

**Comment by prasang-gupta** [comment]
I was implementing it anyways for a requirement. Raised a PR #32 for the same. Let me know your thoughts !
